/**
We allign by company and follow by founder and below which than execute how many users are being implemented upon.
**/
SELECT C.COMPANY_CODE, C.FOUNDER, COUNT(DISTINCT(LM.LEAD_MANAGER_CODE)), COUNT(DISTINCT(SM.SENIOR_MANAGER_CODE)), COUNT(DISTINCT(M.MANAGER_CODE)), COUNT(DISTINCT(E.EMPLOYEE_CODE))
FROM COMPANY AS C
JOIN LEAD_MANAGER AS LM
ON C.COMPANY_CODE = LM.COMPANY_CODE
JOIN SENIOR_MANAGER AS SM
ON C.COMPANY_CODE = SM.COMPANY_CODE
JOIN MANAGER AS M
ON C.COMPANY_CODE = M.COMPANY_CODE
JOIN EMPLOYEE AS E
ON C.COMPANY_CODE = E.COMPANY_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
